### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by RaulFD-creator** [graph-part/graph-part#10]
Hi @fteufel and @mhgislason, my name is Raul Fernandez-Diaz and I am a PhD student currently working on a ML project applied to protein sequences.

I want to include your library in my application by calling the Python API, but I need to know under which license this code is distributed. Could you please tell me?

Thanks beforehand,

**Comment by fteufel** [comment]
Hi Raul,

thanks for raising this! We've added the BSD license to the repo.
