### ISSUE TITLE
Prefilter flag for MMSeqs2 missing from stratified_k_fold

### ISSUE THREAD

**Issue by RaulFD-creator** [graph-part/graph-part#13]
Hi, I was trying to use the `stratified_k_folds` function with the Python API and there is an error that appears when running it with `alignment_mode = 'mmseqs2'` that concerns not having specified the `prefilter` option (whether `True` or `False`). I checked the source code and the flag is missing form the API call to the function. 

I found an easy solution by changing the `api.py` file in the following way:

- Adding in line 81: `prefilter: bool = False,`
- Adding in line 164: `"prefilter": prefilter,`

I have tested it a bit and it seems to be working fine. I may be using this function in a way in which it was not intended to be used, in which case I would appreciate it if you could indicate me how to use the alternative. Otherwise, I hope this may make it easier for you to fix the issue.

To reproduce the error, I was using this call to the API:

```
fold_ids = stratified_k_fold(
        sequences,
        alignment_mode='mmseqs2',
        threads=threads,
        threshold=threshold,
        partitions=n_folds,
        chunks=threads,
        denominator='shortest'
        )
```

Regards,

**Comment by fteufel** [comment]
Hi,

yes, that fix looks correct. The python API is still a bit rough. I'm mainly using graphpart from the commandline myself, so I probably never tested this case.
Will fix it soon.

Thanks for raising!

**Comment by fteufel** [comment]
added missing args.
