### ISSUE TITLE
Bug Report: are sequences ints check in Python API

### ISSUE THREAD

**Issue by RaulFD-creator** [graph-part/graph-part#17]
Hi,

In commit [f2689a1](https://github.com/graph-part/graph-part/commit/116ac0469e28a6a8dc62d69de09fb4a7ba1686e9#diff-7ce379749e457e18196a09d3c2a035602e942a82ab7beeb0e6f8035e26c5e3f2), in lines 179 and 320 a new condition was introduced of the form:

```python
# 'AC' will be type string. But potentially the original 'AC' were ints.
if type(next(sequences.keys())) == int:
```

and it results in the following error:

```
TypeError: 'dict_keys' object is not an iterator
```

I have implemented locally an easy enough solution that I hope may be helpful for you:

```python
if type(list(sequences.keys())[0]) == int:
```

**Comment by fteufel** [comment]
Thanks! I'll add the fix.
